directoki_homepage:
    path:     /
    defaults: { _controller: DirectokiBundle:Default:index }


directoki_project_list:
    path:     /project
    defaults: { _controller: DirectokiBundle:Default:projects }

directoki_project_show:
    path:     /project/{projectId}
    defaults: { _controller: DirectokiBundle:Project:index }

directoki_project_locale_show:
    path:     /project/{projectId}/locale/{localeId}
    defaults: { _controller: DirectokiBundle:ProjectLocale:index }

directoki_project_locale_directory_show:
    path:     /project/{projectId}/locale/{localeId}/directory/{directoryId}
    defaults: { _controller: DirectokiBundle:ProjectLocaleDirectory:index }

directoki_project_locale_directory_record_list:
    path:     /project/{projectId}/locale/{localeId}/directory/{directoryId}/record
    defaults: { _controller: DirectokiBundle:ProjectLocaleDirectory:records }

directoki_project_locale_directory_record_show:
    path:     /project/{projectId}/locale/{localeId}/directory/{directoryId}/record/{recordId}
    defaults: { _controller: DirectokiBundle:ProjectLocaleDirectoryRecord:index }

directoki_admin_project_new:
    path:     /admin/newProject
    defaults: { _controller: DirectokiBundle:AdminDefaultEdit:newProject }

directoki_admin_project_list:
    path:     /admin/project
    defaults: { _controller: DirectokiBundle:AdminDefault:projects }

directoki_admin_project_show:
    path:     /admin/project/{projectId}
    defaults: { _controller: DirectokiBundle:AdminProject:index }

directoki_admin_project_user_list:
    path:     /admin/project/{projectId}/user
    defaults: { _controller: DirectokiBundle:AdminProject:user }

directoki_admin_project_stats:
    path:     /admin/project/{projectId}/stats
    defaults: { _controller: DirectokiBundle:AdminProject:stats }

directoki_admin_project_contact_list:
    path:     /admin/project/{projectId}/contact
    defaults: { _controller: DirectokiBundle:AdminProject:contact }

directoki_admin_project_history_list:
    path:     /admin/project/{projectId}/history
    defaults: { _controller: DirectokiBundle:AdminProject:history }

directoki_admin_project_history_show:
    path:     /admin/project/{projectId}/history/{historyId}
    defaults: { _controller: DirectokiBundle:AdminProjectHistory:index }

directoki_admin_project_locale_list:
    path:     /admin/project/{projectId}/locale
    defaults: { _controller: DirectokiBundle:AdminProject:locale }

directoki_admin_project_locale_new:
    path:     /admin/project/{projectId}/newLocale
    defaults: { _controller: DirectokiBundle:AdminProjectEdit:newLocale }

directoki_admin_project_directory_new:
    path:     /admin/project/{projectId}/newDirectory
    defaults: { _controller: DirectokiBundle:AdminProjectEdit:newDirectory }

directoki_admin_project_directory_show:
    path:     /admin/project/{projectId}/directory/{directoryId}
    defaults: { _controller: DirectokiBundle:AdminProjectDirectory:index }

directoki_admin_project_directory_new_string_field:
    path:     /admin/project/{projectId}/directory/{directoryId}/newField/string
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryEdit:newStringField }

directoki_admin_project_directory_stats:
    path:     /admin/project/{projectId}/directory/{directoryId}/stats
    defaults: { _controller: DirectokiBundle:AdminProjectDirectory:stats }

directoki_admin_project_directory_new_string_with_locale_field:
    path:     /admin/project/{projectId}/directory/{directoryId}/newField/stringWithLocale
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryEdit:newStringWithLocaleField }

directoki_admin_project_directory_new_text_field:
    path:     /admin/project/{projectId}/directory/{directoryId}/newField/text
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryEdit:newTextField }

directoki_admin_project_directory_new_boolean_field:
    path:     /admin/project/{projectId}/directory/{directoryId}/newField/boolean
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryEdit:newBooleanField }

directoki_admin_project_directory_new_latlng_field:
    path:     /admin/project/{projectId}/directory/{directoryId}/newField/latlng
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryEdit:newLatLngField }

directoki_admin_project_directory_new_email_field:
    path:     /admin/project/{projectId}/directory/{directoryId}/newField/email
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryEdit:newEmailField }

directoki_admin_project_directory_new_multi_select_field:
    path:     /admin/project/{projectId}/directory/{directoryId}/newField/multiSelect
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryEdit:newMultiSelectField }

directoki_admin_project_directory_new_url_field:
    path:     /admin/project/{projectId}/directory/{directoryId}/newField/url
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryEdit:newURLField }

directoki_admin_project_directory_fields:
    path:     /admin/project/{projectId}/directory/{directoryId}/field
    defaults: { _controller: DirectokiBundle:AdminProjectDirectory:fields }


directoki_admin_project_directory_field_select_values_list:
    path:     /admin/project/{projectId}/directory/{directoryId}/field/{fieldId}/selectValues
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryField:selectValues }

directoki_admin_project_directory_field_new_select_value:
    path:     /admin/project/{projectId}/directory/{directoryId}/field/{fieldId}/newSelectValue
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryFieldEdit:newSelectValue }


directoki_admin_project_directory_record_list:
    path:     /admin/project/{projectId}/directory/{directoryId}/record
    defaults: { _controller: DirectokiBundle:AdminProjectDirectory:records }

directoki_admin_project_directory_record_list_needing_attention:
    path:     /admin/project/{projectId}/directory/{directoryId}/recordsNeedingAttention
    defaults: { _controller: DirectokiBundle:AdminProjectDirectory:recordsNeedingAttention }

directoki_admin_project_directory_new_record:
    path:     /admin/project/{projectId}/directory/{directoryId}/newRecord
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryEdit:newRecord }

directoki_admin_project_directory_record_show:
    path:     /admin/project/{projectId}/directory/{directoryId}/record/{recordId}
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryRecord:index }

directoki_admin_project_directory_record_contacts:
    path:     /admin/project/{projectId}/directory/{directoryId}/record/{recordId}/contacts
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryRecord:contacts }


directoki_admin_project_directory_record_note_new:
    path:     /admin/project/{projectId}/directory/{directoryId}/record/{recordId}/newNote
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryRecordEdit:newNote }


directoki_admin_project_directory_record_moderate:
    path:     /admin/project/{projectId}/directory/{directoryId}/record/{recordId}/moderate
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryRecordEdit:moderate }

directoki_admin_project_directory_record_report_resolve:
    path:     /admin/project/{projectId}/directory/{directoryId}/record/{recordId}/report/{reportId}/resolve
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryRecordReportEdit:resolve }

directoki_admin_project_directory_record_state_edit_draft:
    path:     /admin/project/{projectId}/directory/{directoryId}/record/{recordId}/editStateDraft
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryRecordEdit:editStateDraft }

directoki_admin_project_directory_record_state_edit_delete:
    path:     /admin/project/{projectId}/directory/{directoryId}/record/{recordId}/editStateDelete
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryRecordEdit:editStateDelete }

directoki_admin_project_directory_record_state_edit_publish:
    path:     /admin/project/{projectId}/directory/{directoryId}/record/{recordId}/editStatePublish
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryRecordEdit:editStatePublish }

directoki_admin_project_directory_record_field_edit:
    path:     /admin/project/{projectId}/directory/{directoryId}/record/{recordId}/field/{fieldId}/edit
    defaults: { _controller: DirectokiBundle:AdminProjectDirectoryRecordFieldEdit:edit }


directoki_api1_project_list_json:
    path:     /api1/projects.json
    defaults: { _controller: DirectokiBundle:API1Default:projectsJSON }


directoki_api1_project_show_json:
    path:     /api1/project/{projectId}/index.json
    defaults: { _controller: DirectokiBundle:API1Project:indexJSON }


directoki_api1_project_directories_json:
    path:     /api1/project/{projectId}/directories.json
    defaults: { _controller: DirectokiBundle:API1Project:directoriesJSON }


directoki_api1_project_directory_show_json:
    path:     /api1/project/{projectId}/directory/{directoryId}/index.json
    defaults: { _controller: DirectokiBundle:API1ProjectDirectory:indexJSON }

directoki_api1_project_directory_field_list_json:
    path:     /api1/project/{projectId}/directory/{directoryId}/fields.json
    defaults: { _controller: DirectokiBundle:API1ProjectDirectory:fieldsJSON }

directoki_api1_project_directory_field_list_jsonp:
    path:     /api1/project/{projectId}/directory/{directoryId}/fields.jsonp
    defaults: { _controller: DirectokiBundle:API1ProjectDirectory:fieldsJSONP }

directoki_api1_project_directory_field_show_json:
    path:     /api1/project/{projectId}/directory/{directoryId}/field/{fieldId}/index.json
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryField:indexJSON }

directoki_api1_project_directory_field_show_jsonp:
    path:     /api1/project/{projectId}/directory/{directoryId}/field/{fieldId}/index.jsonp
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryField:indexJSONP }

directoki_api1_project_directory_field_select_values_json:
    path:     /api1/project/{projectId}/directory/{directoryId}/field/{fieldId}/selectValues.json
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryField:selectValuesJSON }

directoki_api1_project_directory_field_select_values_jsonp:
    path:     /api1/project/{projectId}/directory/{directoryId}/field/{fieldId}/selectValues.jsonp
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryField:selectValuesJSONP }

directoki_api1_project_directory_record_list_json:
    path:     /api1/project/{projectId}/directory/{directoryId}/records.json
    defaults: { _controller: DirectokiBundle:API1ProjectDirectory:recordsJSON }

directoki_api1_project_directory_new_record_json:
    path:     /api1/project/{projectId}/directory/{directoryId}/newRecord.json
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryEdit:newRecordJSON }

directoki_api1_project_directory_new_record_jsonp:
    path:     /api1/project/{projectId}/directory/{directoryId}/newRecord.jsonp
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryEdit:newRecordJSONP }

directoki_api1_project_directory_record_show_json:
    path:     /api1/project/{projectId}/directory/{directoryId}/record/{recordId}/index.json
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryRecord:indexJSON }

directoki_api1_project_directory_record_show_jsonp:
    path:     /api1/project/{projectId}/directory/{directoryId}/record/{recordId}/index.jsonp
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryRecord:indexJSONP }

directoki_api1_project_directory_record_edit_json:
    path:     /api1/project/{projectId}/directory/{directoryId}/record/{recordId}/edit.json
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryRecordEdit:editJSON }

directoki_api1_project_directory_record_edit_jsonp:
    path:     /api1/project/{projectId}/directory/{directoryId}/record/{recordId}/edit.jsonp
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryRecordEdit:editJSONP }

directoki_api1_project_directory_record_new_report_jsonp:
    path:     /api1/project/{projectId}/directory/{directoryId}/record/{recordId}/newReport.jsonp
    defaults: { _controller: DirectokiBundle:API1ProjectDirectoryRecordEdit:newReportJSONP }
